---
# forum
#
# Dependencies:
#
#   * common
#   * docker_ce

- name: create application user
  user:
    name: "{{ forum_user }}"
    home: "{{ forum_app_dir }}"
    createhome: yes
    shell: /bin/false
    generate_ssh_key: yes
  notify: restart the forum_docker service
  tags:
    - install
    - install:base

# Ensure the directory is accessible to the web service
- name: set forum app dir permissions
  file:
    path: "{{ forum_app_dir }}"
    state: directory
    owner: "{{ forum_user }}"
    group: "{{ common_web_group }}"
  notify: restart the forum_docker service
  tags:
    - install
    - install:base

- name: setup the forum env for stage/prod
  template:
    src: forum_env.j2
    dest: "{{ forum_app_dir }}/forum_env"
    owner: "{{ forum_user }}"
    group: "{{ common_web_user }}"
    mode: 0644
  notify:
    - restart the forum_docker service
  tags:
    - install
    - install:base
    - install:configuration
  with_items:
    - "{{ forum_env }}"

- name: create {{ forum_data_dir }}
  file:
    path: "{{ forum_data_dir }}"
    state: directory
    owner: "{{ common_web_user }}"
    group: "{{ common_web_group }}"
    mode: 0777
  tags:
    - install
    - install:base

- include: deploy.yml
  tags:
    - deploy
