---

BACKUPS_MYSQL: yes
BACKUPS_MONGO: yes
BACKUPS_MONGO_USER: 'admin'
BACKUPS_MONGO_PASSWORD: 'password'
BACKUPS_BUCKET: ''
BACKUPS_DIR: '/tmp/db_backups'
BACKUPS_SENTRY_DSN: ''
BACKUPS_RUN_DURING_DEPLOYMENT: yes

# gs: Google Cloud Storage
# s3: Amazon Simple Storage Service
BACKUPS_PROVIDER: 'gs'

# AWS
BACKUPS_AWS_ACCESS_KEY_ID: ''
BACKUPS_AWS_SECRET_ACCESS_KEY: ''

# Google Cloud Storage
BACKUPS_GS_BOTO_FILE: '/root/.boto'
BACKUPS_GS_DEFAULT_PROJECT_ID: ''
BACKUPS_GS_SERVICE_KEY_CONTENTS: ''
BACKUPS_GS_SERVICE_KEY_FILE: '/root/backup-service-account.p12'
BACKUPS_GS_SERVICE_CLIENT_ID: ''
BACKUPS_GS_SERVICE_KEY_FILE_PASSWORD: 'notasecret'

# Azure
BACKUPS_AZURE_STORAGE_ACCOUNT: ''
BACKUPS_AZURE_STORAGE_KEY: ''

# Prometheus Pushgateway
PUSHGATEWAY: 'https://pushgateway.infra.appsembler.com'
