- name: Include edxapp vars
  include_vars:
    file: ../../edxapp/defaults/main.yml
  tags:
    - custom_domains
    - custom_domains:get_domains

- name: "Fetch custom domains list"
  become_user: "{{ edxapp_user }}"
  django_manage: >
    command="lms custom_domains_list"
    app_path="{{ edxapp_code_dir }}"
    settings="{{ EDXAPP_SETTINGS }}"
    pythonpath="{{ edxapp_code_dir }}"
    virtualenv="{{ edxapp_venv_dir }}"
  register: custom_domains_cmd
  run_once: True
  delegate_to: "{{ groups['edx'][0] }}"
  tags:
    - custom_domains
    - custom_domains:get_domains

- name: Set fact letsencrypt_certs
  set_fact:
    letsencrypt_certs: "{{ custom_domains_cmd.out|from_json }}"
  tags:
    - custom_domains
    - custom_domains:get_domains

- name: Print letsencrypt_certs
  debug:
    var: letsencrypt_certs
  tags:
    - custom_domains
    - custom_domains:debug

