- name: Include edxapp vars
  include_vars:
    file: ../../edxapp/defaults/main.yml
  tags:
    - custom_domains
    - custom_domains:get_domains

- debug:
    var: edxapp_venv_bin
- debug:
    var: EDXAPP_SETTINGS
- debug:
    var: edxapp_code_dir
- debug:
    var: groups
    
- name: Fetch custom domains list
  shell: >
    {{ edxapp_venv_bin }}/python manage.py lms --setting={{ EDXAPP_SETTINGS }} custom_domains_list
    chdir={{ edxapp_code_dir }}
  become_user: "{{ edxapp_user }}"
  register: custom_domains_cmd
  run_once: True
  delegate_to: "{{ groups['edx'][1] }}"
  tags:
    - custom_domains
    - custom_domains:get_domains

- debug:
    var: custom_domains_cmd

- name: Set fact letsencrypt_certs
  set_fact:
    letsencrypt_certs: "{{ custom_domains_cmd.stdout|from_json }}"
  tags:
    - custom_domains
    - custom_domains:get_domains

- name: Print letsencrypt_certs
  debug:
    var: letsencrypt_certs
  tags:
    - custom_domains
    - custom_domains:debug

