---

# write the supervisor script for celery workers
- name: writing celery supervisor scripts
  template:
    src: "edx/app/supervisor/conf.d.available/{{ item }}.j2"
    dest: "{{ supervisor_available_dir }}/{{ item }}"
    owner: "{{ supervisor_user }}"
    group: "{{ supervisor_user }}"
    mode: 0644
  become_user: "{{ supervisor_user }}"
  with_items:
    - workers.conf
  tags:
    - install
    - install:configuration

- name: writing celerybeat supervisor scripts
  template:
    src: "celerybeat.conf.j2"
    dest: "{{ supervisor_available_dir }}/celerybeat.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ supervisor_user }}"
    mode: 0644
  become_user: "{{ supervisor_user }}"
  tags:
    - install
    - install:configuration
    - install:celerybeat
  when:
   - EDXAPP_CELERY_BEAT_LMS_ENABLED or EDXAPP_CELERY_BEAT_CMS_ENABLED

- name: "enable celerybeat supervisor script"
  file:
    src: "{{ supervisor_available_dir }}/celerybeat.conf"
    dest: "{{ supervisor_cfg_dir }}/celerybeat.conf"
    state: link
    force: yes
  become_user: "{{ supervisor_user }}"
  when:
    - celery_worker is defined and not disable_edx_services
    - EDXAPP_CELERY_BEAT_LMS_ENABLED or EDXAPP_CELERY_BEAT_CMS_ENABLED
  tags:
    - install
    - install:configuration
    - install:celerybeat

- name: enable celery worker supervisor script
  file:
    src: "{{ supervisor_available_dir }}/workers.conf"
    dest: "{{ supervisor_cfg_dir }}/workers.conf"
    state: link
    force: yes
  become_user: "{{ supervisor_user }}"
  when: celery_worker is defined and not disable_edx_services
  tags:
    - install
    - install:configuration
