---
- name: recompile SASS
  django_manage:
    app_path: "{{ edxapp_code_dir }}"
    command: "lms recompile_site_sass"
    settings: "{{ EDXAPP_SETTINGS }}"
    virtualenv: "{{ edxapp_venv_dir }}"
  environment: "{{ edxapp_environment }}"
  ignore_errors: yes
