- name: Create css directories for microsites
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ edxapp_user }}"
    group: "{{ common_web_group }}"
    mode: "777"
    recurse: yes
  with_items:
    - { path: "{{ amc_customer_themes_dir }}" }
  tags:
    - deploy

- name: Make default SiteConfiguration for settings.SITE_ID
  become_user: "{{ edxapp_user }}"
  shell: |
    cd {{ edxapp_code_dir }}
    source {{ edxapp_app_dir }}/edxapp_env
    {{ edxapp_venv_bin }}/python manage.py lms --setting={{ EDXAPP_SETTINGS }} create_default_site_config
  args:
    executable: /bin/bash
  run_once: True
  tags:
    - deploy

- name: Copy over helper (workon like) script
  copy: src=edx.sh dest=/usr/local/bin/edx mode=0755
  tags:
    - install
    - install:configuration
    - deploy

