- name: Deploy all analytics services to a single node
  hosts: insights-server
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
    elasticsearch_repo: "deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main"
    ELASTICSEARCH_VERSION: "1.5.2"
  roles:
    - sudo
    - { role: mysql_init, tags: ['mysql_init_role'] }
    - { role: memcache, tags: ['memcache_role'] }
    - { role: elasticsearch, tags: ['elasticsearch_role'] }
    - { role: analytics_api, tags: ['analytics_api_role'] }
    - { role: insights, tags: ['insights_role'] }
    - role: nginx
      nginx_sites:
        - insights
      tags: ['nginx_role']
    - { role: insights_tracking_logs_sync, tags: ['insights_tracking_logs_sync_role'] }
