---

- name: Install python2 on EC2 instance
  hosts: jenkins-scheduler
  sudo: yes
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: "Update apt-get"
      raw: sudo apt-get update -y
    - name: "install python2 and python-simplejson"
      raw: sudo apt-get -y install python-simplejson

- name: Configure instance(s)
  hosts: jenkins-scheduler
  become: True
  roles:
  - jenkins_analytics
  - jenkins_configuration
