---

# Appsembler basic tier deployment

- include: monitoring.yml

- name: Configure basic tier instance
  hosts: edxapp-server
  become: True
  become_method: sudo
  gather_facts: True
  vars:
    appsembler_roles: "../../../appsembler-roles"
    migrate_db: "yes"
    SANDBOX_ENABLE_ECOMMERCE: False
    COMMON_ENABLE_INSIGHTS: False
    COMMON_ENABLE_OAUTH_CLIENT: False
    COMMON_ENABLE_BACKUPS: True
    ENABLE_ECOMMERCE: false
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB", tags: ['swapfile_role'] }
    - sudo
    - { role: aws, tags: ['aws_role'] }
    - role: nginx
      nginx_sites: []
      tags: ['nginx_role']
    - role: "{{ appsembler_roles }}/letsencrypt"
      when: letsencrypt_certs | length
    - role: "{{ appsembler_roles }}/sshguard"
      when:
        - sshguard_whitelist | length
      tags: ['sshguard_role']
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - xqueue
      - edx_notes_api
      nginx_default_sites:
      - lms
      tags: ['nginx_role']
    - { role: mysql, tags: ['mysql_role'] }
    - { role: mysql_init, tags: ['mysql_init_role'] }
    - role: memcache
      when: "'localhost' in ' '.join(EDXAPP_MEMCACHE)"
      tags: ['memcache_role']
    - role: mongo_3_2
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
      tags: ['mongo_3_2_role']
    - { role: rabbitmq, rabbitmq_ip: '127.0.0.1', tags: ['rabbitmq_role'] }
    - { role: edxapp, celery_worker: True, tags: ['edxapp_role'] }
    - { role: edxapp, tags: ['edxapp_role'] }
    - { role: notifier, tags: ['notifier_role'] }
    - role: edx_notes_api
      when: "INSTALL_EDX_NOTES is defined and INSTALL_EDX_NOTES"
      tags: ['edx_notes_api_role']
    - role: demo
      when: "INSTALL_DEMO_DATA"
      tags: ['demo_role']
    - role: oauth_client_setup
      when: COMMON_ENABLE_OAUTH_CLIENT
      tags: ['oauth_client_setup_role']
    - { role: oraclejdk, tags: ['oraclejdk_role'] }
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"
      tags: ['elasticsearch_role']
    - { role: forum, tags: ['forum_role'] }
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5", tags: ['notifier_role'] }
    - { role: xqueue, update_users: True, tags: ['xqueue_role'] }
    - { role: backups, BACKUPS_MONGO: True, BACKUPS_MYSQL: True, when: COMMON_ENABLE_BACKUPS }
    - role: ecommerce
      when: ENABLE_ECOMMERCE
      tags: ['ecommerce_role']
    - role: ecomworker
      when: ENABLE_ECOMMERCE
      tags: ['ecomworker_role']
    - role: ecommerce_theme
      when: ENABLE_ECOMMERCE
      tags: ['ecommerce_theme_role']
    - role: appsembler_reporting
      when: 
        - "EDXAPP_APPSEMBLER_FEATURES.ENABLE_APPSEMBLER_REPORTING|default(false)"
        - "COMMON_ENVIRONMENT == 'prod'"
      tags: ['appsembler_reporting_role']
