---

- name: Configure monitoring tools
  hosts: all
  become: True
  become_method: sudo
  gather_facts: True
  vars:
    appsembler_roles: "../../../appsembler-roles"
  roles:
    - sysdig
    - oraclejdk

    - role: "{{ appsembler_roles }}/filebeat"
      when: "LOGSTASH_ENABLED|default(False)"

    - role: "{{ appsembler_roles }}/logstash"
      when: "LOGSTASH_ENABLED|default(False)"

    - role: "{{ appsembler_roles }}/stackdriver"
      when: "cloud_provider == 'gcp'"

    - "{{ appsembler_roles }}/monit"

    - role: "{{ appsembler_roles }}/snort"
      when: "SNORT_ENABLED|default(True)"
