# CONFIGURE NGINX
# SYNC LOCAL SCORM CONTENT PACKAGES WITH S3 IF NOT STORED THERE TO BEGIN WITH

# do these as includes since Vagrant  < 2.0 doesn't obey
# conditionals to include the whole scorm role


# as it is possible to set Site-specific configuration of the SCORM XBlock
# using SiteConfiguration object values, make sure that all
# players which must be installed are defined as options in the base 
# XBlock settings defined in Ansible variables.  SiteConfiguration for 
# specific Sites can override the SCORM_PLAYER_BACKENDS option to remove
# player options that are not relevant to the Site
- name: define scorm config from settings if available
  set_fact: 
    scorm_config: "{{ EDXAPP_XBLOCK_SETTINGS.ScormXBlock|default('{}') }}"

- include_vars: ../../edxapp/defaults/main.yml
- include_vars: ../../nginx/defaults/main.yml    

- include: scorm_base.yml
  when: EDXAPP_XBLOCK_SETTINGS.ScormXBlock is defined

- include: scorm_backup.yml
  when: 
    - EDXAPP_XBLOCK_SETTINGS.ScormXBlock is defined
    - SCORM_S3_BACKUP

- include: scorm_players.yml
  when: 
    - EDXAPP_XBLOCK_SETTINGS.ScormXBlock is defined
    - EDXAPP_AUTH_EXTRA.SCORMPLAYER_GIT_IDENTITIES is defined
