---

- name: Configure Mongo
  hosts: mongo
  become: True
  become_method: sudo
  gather_facts: True
  roles:
    - mongo_3_2

- name: Configure shared services (es, memcached, rabbitmq)
  hosts: services
  become: True
  become_method: sudo
  gather_facts: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB" }
    - role: sudo
    - edxapp_common
    - edx_ansible
    - gcsfuse_role
    - oraclejdk
    - elasticsearch
    - memcached
    - certagent_role
    - google_fluentd_role
    - node_exporter_role
    - { role: 'rabbitmq', rabbitmq_ip: '0.0.0.0' }
    - mysql_init
    - role: credentials
      when: TAHOE_CREDENTIALS_ENABLE|default(false)
      tags: credentials_role
    - { role: deploy_info }

- name: Deploy edxapp workers
  hosts: workers
  become: True
  become_method: sudo
  gather_facts: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB" }
    - role: sudo
    - role: aws
    - mysql_init
    - role: node_exporter_role
      node_exporter_enabled_collectors:
        - systemd
        - supervisord
        - textfile:
            directory: "{{ node_exporter_textfile_dir }}"
        - filesystem:
            ignored-mount-points: "^/(sys|proc|dev|var|run)($|/)"
            ignored-fs-types: "^(sys|proc|auto|shm|tmp|ns)fs$"
    - role: edxapp
      celery_worker: True
    - google_fluentd_role
    - { role: deploy_info }

# first, do everything we can safely do in parallel
- name: app server common setup
  hosts: edx
  become: True
  become_method: sudo
  gather_facts: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - role: sudo
    - role: aws
    - scriabin
    - nxmon_role
    - google_fluentd_role
    - role: node_exporter_role
      node_exporter_enabled_collectors:
        - systemd
        - supervisord
        - textfile:
            directory: "{{ node_exporter_textfile_dir }}"
        - filesystem:
            ignored-mount-points: "^/(sys|proc|dev|var|run)($|/)"
            ignored-fs-types: "^(sys|proc|auto|shm|tmp|ns)fs$"

# rolling deploy to one at a time
- name: Configure app server instance(s)
  hosts: edx
  become: True
  become_method: sudo
  gather_facts: True
  serial: 1
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
  pre_tasks:
    - name: remove from load balancer
      service:
        name: nginx
        state: stopped
      ignore_errors: yes  # Ignore the errors on this because it could potentially be the first 
                                     # deploy to a new server, in which case nginx would not yet be installed.
      tags:
        - deploy
  roles:
    - mysql_init
    - role: mysql
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - role: mongo_3_2
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    - edxapp
    - custom_domains # This gets a list of custom domains
    - gcsfuse_role
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - health-check
      nginx_default_sites:
      - lms
    - fix_dir_perms_role
    - amc
    - oauth_client_setup
    - { role: letsencrypt_role, letsencrypt_run: false }
    - { role: deploy_info, tags: ['deploy'] }
  post_tasks:
    - name: re-add to load balancer
      service:
        name: nginx
        state: started
      retries: 3
      delay: 60
      register: task_result
      until: task_result is succeeded
      tags:
        - deploy

- name: Deploy forum
  hosts: forum
  become: True
  tags: forum
  gather_facts: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB" }
    - role: sudo
    - role: aws
    - role: nginx
      nginx_sites:
      - forum
    - role: docker_ce
      tags: ['forum_role']
    - role: forum_docker
      tags: ['forum_role']
    - google_fluentd_role
    - role: node_exporter_role
      node_exporter_enabled_collectors:
        - systemd
        - supervisord
        - textfile:
            directory: "{{ node_exporter_textfile_dir }}"
        - filesystem:
            ignored-mount-points: "^/(sys|proc|dev|var|run)($|/)"
            ignored-fs-types: "^(sys|proc|auto|shm|tmp|ns)fs$"
    - { role: deploy_info }

# TODO: Fix the notifier. It's breaking the Ansible deployments. See RED-133
#- name: Install xqueue and notifier on services node
#  hosts: "services"
#  become: True
#  become_method: sudo
#  gather_facts: True
#  vars:
#    migrate_db: "yes"
#  roles:
#    - mysql_init
#    - edxapp_common
#    - role: nginx
#      nginx_sites:
#      - xqueue
#    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
#    - { role: "xqueue", update_users: True }
#    - role: custom_domains # This gets the list of domains
#      when: nginx_enable_custom_domains|default(False)
#    - { role: letsencrypt_role, letsencrypt_webserver: "" }
