# Playbook for adding/updating custom domains
# this playbook gets run by Tahoe Cert Agent when a new custom domain
# is registered.
# The goal is not to install things (it expects that the whole system
# is already installed and ready). It just sets up the config and
# fetches a SSL certificate for the new domain.

---

- name: Configure app server instance(s)
  hosts: edx
  become: True
  become_method: sudo
  gather_facts: True
  vars:
    appsembler_roles: "../../appsembler-roles"
    EDXAPP_LMS_NGINX_PORT: '80'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
  roles:
    - custom_domains # This gets a list of custom domains
    - { role: "{{ appsembler_roles }}/letsencrypt", letsencrypt_run: false }
    - role: nginx
