---

# write the supervisor scripts for the service variants
- name: "writing {{ item }} supervisor script"
  template:
    src: "edx/app/supervisor/conf.d.available/{{ item }}.conf.j2"
    dest: "{{ supervisor_available_dir }}/{{ item }}.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ supervisor_user }}"
    mode: 0644
  become_user: "{{ supervisor_user }}"
  with_items: "{{ service_variants_enabled }}"
  tags:
    - install
    - install:configuration

- name: add gunicorn configuration files
  template:
    src: "{{ item }}_gunicorn.py.j2"
    dest: "{{ edxapp_app_dir }}/{{ item }}_gunicorn.py"
    mode: 0644
  become_user: "{{ edxapp_user }}"
  with_items: "{{ service_variants_enabled }}"
  tags:
    - install
    - install:configuration

# Enable the supervisor jobs
- name: "enable {{ item }} supervisor script"
  file:
    src: "{{ supervisor_available_dir }}/{{ item }}.conf"
    dest: "{{ supervisor_cfg_dir }}/{{ item }}.conf"
    state: link
    force: yes
  become_user: "{{ supervisor_user }}"
  with_items: "{{ service_variants_enabled }}"
  when: celery_worker is not defined and not disable_edx_services
  tags:
    - install
    - install:configuration
