---

- name: restart edxapp
  supervisorctl:
    name: "{{ item }}"
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: restarted
  when: edxapp_installed is defined and celery_worker is not defined and not disable_edx_services
  become_user: "{{ supervisor_service_user }}"
  with_items:
    - 'lms'
    - 'cms'
  tags:
    - manage
    - deploy:platform
